WIP: Fix for DBAL 2.11 and functional tests
facile-it/doctrine-mysql-come-back pull request #40
Opened 2020-10-17 14:34 UTC by thomasvargiu

2020-10-17 20:16 UTC, jdreesen commented on CHANGELOG.md
> + * Bumped minimum PHP version to 7.2
In `composer.json` it says `^7.3`.

2020-10-18 09:41 UTC, thomasvargiu commented on CHANGELOG.md
> + * Bumped minimum PHP version to 7.2
thanks

2020-10-19 10:00 UTC, lkck24 approved these changes

2020-10-22 15:19 UTC, lkck24 commented
I can confirm, that master is broken currently and this PR fixes master.

2020-10-26 08:45 UTC, Jean85 requested changes

2020-10-26 08:45 UTC, Jean85 commented on tests/functional/FunctionalTest.php
> +        $this->expectException(DBALException::class);
Please move this line to the last sensible moment, to avoid false greens.

2020-10-26 08:45 UTC, Jean85 commented on tests/functional/FunctionalTest.php
> +        $connection->executeUpdate('UPDATE test SET updatedAt = CURRENT_TIMESTAMP WHERE id = 1');
Shouldn't write queries fail?

2020-10-26 08:45 UTC, Jean85 commented on tests/unit/ConnectionTest.php
> +        $this->expectException(InvalidArgumentException::class);
Here too: these assertions should be used at the last moment.

2020-10-30 08:57 UTC, Jean85 approved these changes

2020-10-30 08:57 UTC, merged